# Create Desktop Shortcut for Project Greenlight
$WshShell = New-Object -ComObject WScript.Shell
$Shortcut = $WshShell.CreateShortcut("$env:USERPROFILE\Desktop\Project Greenlight.lnk")
$Shortcut.TargetPath = "$PSScriptRoot\launch_greenlight.bat"
$Shortcut.WorkingDirectory = $PSScriptRoot
$Shortcut.Description = "Launch Project Greenlight"
# Use custom stoplight icon generated by OmniMind
$IconPath = "$PSScriptRoot\greenlight_icon.ico"
if (Test-Path $IconPath) {
    $Shortcut.IconLocation = $IconPath
} else {
    $Shortcut.IconLocation = "shell32.dll,41"  # Fallback to green folder icon
}
$Shortcut.Save()

Write-Host "Desktop shortcut created: Project Greenlight.lnk" -ForegroundColor Green
if (Test-Path $IconPath) {
    Write-Host "Using custom stoplight icon: $IconPath" -ForegroundColor Cyan
}

